version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/facilitator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/facilitator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/key-rotator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/key-rotator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/cluster_bootstrap"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/workflow-manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/workflow-manager"
    schedule:
      interval: "weekly"
