name: push-docker-image

on:
  release:
    types: [published]

jobs:
  push-facilitator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: isrgautomaton
        password: ${{ secrets.ISRG_AUTOMATON_DOCKERHUB_AUTH_TOKEN }}
    - name: update-version
      run: sed -i "s/^version =.*/version = \"${{ steps.get_version.outputs.VERSION }}\"/" facilitator/Cargo.toml
    - name: build
      run: ./facilitator/build.sh
    - name: tag
      run: docker tag letsencrypt/prio-facilitator letsencrypt/prio-facilitator:${{ steps.get_version.outputs.VERSION }}
    - name: push
      run: docker push letsencrypt/prio-facilitator:${{ steps.get_version.outputs.VERSION }}

  push-workflow-manager:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: isrgautomaton
        password: ${{ secrets.ISRG_AUTOMATON_DOCKERHUB_AUTH_TOKEN }}
    - name: build
      run: ./workflow-manager/build.sh
    - name: tag
      run: docker tag letsencrypt/prio-workflow-manager letsencrypt/prio-workflow-manager:${{ steps.get_version.outputs.VERSION }}
      - name: push
      run: docker push letsencrypt/prio-workflow-manager:${{ steps.get_version.outputs.VERSION }}
